In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## **DATA COLLECTION**

In [ ]:
deliveries_data = pd.read_csv('/content/IPL_PER_MATCH_DATA_2008_2020.csv')

match_data = pd.read_csv('/content/IPL_Matches_2008-2020.csv')

In [ ]:
match_data.head(4)

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper

In [ ]:
match_data.columns

Index(['id', 'city', 'date', 'player_of_match', 'venue', 'neutral_venue',
       'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'result',
       'result_margin', 'eliminator', 'method', 'umpire1', 'umpire2'],
      dtype='object')

### **SOME BASIC ANALYSIS OF MATCHES DATA**

**1) Total matches played**

In [ ]:
match_data.shape

(816, 17)

In [ ]:
match_data.shape[0]

816

**2) Venue of Matches (city and stadium) **

In [ ]:
match_data['venue'].unique()

array(['M Chinnaswamy Stadium',
       'Punjab Cricket Association Stadium, Mohali', 'Feroz Shah Kotla',
       'Wankhede Stadium', 'Eden Gardens', 'Sawai Mansingh Stadium',
       'Rajiv Gandhi International Stadium, Uppal',
       'MA Chidambaram Stadium, Chepauk', 'Dr DY Patil Sports Academy',
       'Newlands', "St George's Park", 'Kingsmead', 'SuperSport Park',
       'Buffalo Park', 'New Wanderers Stadium', 'De Beers Diamond Oval',
       'OUTsurance Oval', 'Brabourne Stadium',
       'Sardar Patel Stadium, Motera', 'Barabati Stadium',
       'Vidarbha Cricket Association Stadium, Jamtha',
       'Himachal Pradesh Cricket Association Stadium', 'Nehru Stadium',
       'Holkar Cricket Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Subrata Roy Sahara Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium',
       'Sharjah Cricket Stadium', 'Dubai International Cricket Stadium',
       'Maharashtra Cricket Association Stadium',
       'Punjab Cricket Association IS Bindra Stadium, Mohali',
       'Saurashtra Cricket Association Stadium', 'Green Park',
       'M.Chinnaswamy Stadium'], dtype=object)

In [ ]:
match_data['city'].unique()

array(['Bangalore', 'Chandigarh', 'Delhi', 'Mumbai', 'Kolkata', 'Jaipur',
       'Hyderabad', 'Chennai', 'Cape Town', 'Port Elizabeth', 'Durban',
       'Centurion', 'East London', 'Johannesburg', 'Kimberley',
       'Bloemfontein', 'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala',
       'Kochi', 'Indore', 'Visakhapatnam', 'Pune', 'Raipur', 'Ranchi',
       'Abu Dhabi', nan, 'Rajkot', 'Kanpur', 'Bengaluru', 'Dubai',
       'Sharjah'], dtype=object)

**3) Total teams participated**

In [ ]:
match_data['team1'].unique()  ## Total teams participated

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Rajasthan Royals', 'Deccan Chargers', 'Chennai Super Kings',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant', 'Delhi Capitals'], dtype=object)

**4) Maximum Toss Winner Teams**

In [ ]:
match_data['toss_winner'].value_counts()

toss_winner
Mumbai Indians                 106
Kolkata Knight Riders           98
Chennai Super Kings             97
Rajasthan Royals                87
Royal Challengers Bangalore     87
Kings XI Punjab                 85
Delhi Daredevils                80
Sunrisers Hyderabad             57
Deccan Chargers                 43
Pune Warriors                   20
Delhi Capitals                  20
Gujarat Lions                   15
Kochi Tuskers Kerala             8
Rising Pune Supergiants          7
Rising Pune Supergiant           6
Name: count, dtype: int64

**5) Most player of the match won**

In [ ]:
match_data['player_of_match'].value_counts().index[0] ## Most Player of the match won

'AB de Villiers'

#  Section 1 — Rohit Sharma Batting Analysis

In [ ]:
deliveries_data['batsman'].unique() ## finding all the unique batsman ..

array(['RT Ponting', 'BB McCullum', 'DJ Hussey', 'Mohammad Hafeez',
       'SC Ganguly', 'CL White', 'MV Boucher', 'B Akhil', 'AA Noffke',
       'P Kumar', 'Z Khan', 'SB Joshi', 'W Jaffer', 'JH Kallis',
       'R Dravid', 'V Kohli', 'K Goel', 'MEK Hussey', 'JR Hopes',
       'SK Raina', 'JDP Oram', 'S Badrinath', 'PA Patel', 'ML Hayden',
       'MS Dhoni', 'KC Sangakkara', 'Yuvraj Singh', 'SM Katich',
       'IK Pathan', 'T Kohli', 'YK Pathan', 'S Dhawan', 'G Gambhir',
       'SK Warne', 'D Salunkhe', 'SK Trivedi', 'V Sehwag', 'SR Watson',
       'M Kaif', 'DS Lehmann', 'RA Jadeja', 'M Rawat', 'L Ronchi',
       'ST Jayasuriya', 'DJ Thornely', 'RV Uthappa', 'PR Shah',
       'AM Nayar', 'SM Pollock', 'Harbhajan Singh', 'S Chanderpaul',
       'LRPL Taylor', 'WP Saha', 'AS Yadav', 'A Symonds', 'SB Bangar',
       'WPUJC Vaas', 'RP Singh', 'AC Gilchrist', 'Y Venugopal Rao',
       'VVS Laxman', 'RG Sharma', 'SB Styris', 'LR Shukla', 'PP Chawla',
       'Kamran Akmal', 'DPMD Jayawardene', 'S Sohal', 'B Lee', 'WA Mota',
       'Shahid Afridi', 'DJ Bravo', 'A Nehra', 'MA Khote', 'GC Smith',
       'Pankaj Singh', 'S Sreesanth', 'VRV Singh', 'SS Tiwary',
       'RR Sarwan', 'DS Kulkarni', 'R Vinay Kumar', 'M Kartik',
       'I Sharma', 'AB Agarkar', 'AM Rahane', 'TM Srivastava',
       'Shoaib Malik', 'MK Tiwary', 'KD Karthik', 'R Bhatia',
       'MF Maharoof', 'VY Mahesh', 'B Chipli', 'DW Steyn', 'DB Das',
       'MK Pandey', 'HH Gibbs', 'DNT Zoysa', 'D Kalyankrishna',
       'SE Marsh', 'SA Asnodkar', 'BJ Hodge', 'Sohail Tanvir',
       'Salman Butt', 'Umar Gul', 'AB Dinda', 'AB de Villiers',
       'SP Fleming', 'S Vidyut', 'JA Morkel', 'LPC Silva', 'DB Ravi Teja',
       'Misbah-ul-Haq', 'PJ Sangwan', 'YV Takawale', 'RR Raje',
       'Mohammad Asif', 'GD McGrath', 'Joginder Sharma', 'MS Gony',
       'M Muralitharan', 'M Ntini', 'DT Patil', 'A Kumble', 'S Anirudha',
       'MM Patel', 'CK Kapugedera', 'A Chopra', 'T Taibu', 'J Arunkumar',
       'PP Ojha', 'SP Goswami', 'SR Tendulkar', 'U Kaul', 'Niraj Patel',
       'AD Mascarenhas', 'TM Dilshan', 'A Mishra', 'LA Pomersbach',
       'Iqbal Abdulla', 'Younis Khan', 'PM Sarvesh Kumar',
       'DP Vijaykumar', 'Shoaib Akhtar', 'Abdur Razzak', 'H Das',
       'DR Smith', 'SD Chitnis', 'CRD Fernando', 'VS Yeligati',
       'L Balaji', 'A Mukund', 'RR Powar', 'JP Duminy', 'A Flintoff',
       'T Thushara', 'KP Pietersen', 'JD Ryder', 'T Henderson',
       'Kamran Khan', 'RS Bopara', 'MC Henriques', 'CH Gayle',
       'R Bishnoi', 'KV Sharma', 'FH Edwards', 'AS Raut', 'PC Valthaty',
       'RJ Quiney', 'Yashpal Singh', 'M Manhas', 'AA Bilakhia',
       'AN Ghosh', 'BAW Mendis', 'DL Vettori', 'MN van Wyk',
       'RE van der Merwe', 'TL Suman', 'Shoaib Ahmed', 'GR Napier',
       'KP Appanna', 'LA Carseldine', 'NV Ojha', 'SM Harwood', 'M Vijay',
       'DA Warner', 'SB Jakati', 'RJ Harris', 'D du Preez', 'M Morkel',
       'AD Mathews', 'SL Malinga', 'C Nanda', 'J Botha',
       'Mashrafe Mortaza', 'A Singh', 'GJ Bailey', 'AB McDonald',
       'Y Nagar', 'SS Shaikh', 'R Ashwin', 'Mohammad Ashraful',
       'Jaskaran Singh', 'Anirudh Singh', 'CA Pujara', 'OA Shah',
       'AP Tare', 'AT Rayudu', 'R Sathish', 'R McLaren',
       'AA Jhunjhunwala', 'P Dogra', 'A Uniyal', 'MS Bisla', 'YA Abdulla',
       'EJG Morgan', 'JM Kemp', 'S Tyagi', 'RS Gavaskar', 'SE Bond',
       'S Ladda', 'DP Nannes', 'KA Pollard', 'DR Martyn', 'S Narwal',
       'MJ Lumb', 'Bipul Sharma', 'AB Barath', 'FY Fazal', 'AC Voges',
       'MD Mishra', 'UT Yadav', 'J Theron', 'SJ Srivastava', 'R Sharma',
       'Mandeep Singh', 'KM Jadhav', 'SW Tait', 'KB Arun Karthik',
       'KAJ Roach', 'PD Collingwood', 'CK Langeveldt', 'VS Malik',
       'A Mithun', 'AP Dole', 'AN Ahmed', 'RS Sodhi', 'DE Bollinger',
       'S Sriram', 'B Sumanth', 'C Madan', 'AG Paunikar', 'MR Marsh',
       'AJ Finch', 'STR Binny', 'Harmeet Singh', 'IR Jaggi',
       'DT Christian', 'MA Agarwal', 'RV Gomez', 'AUK Pathan',
       'UBT Chand', 'DJ Jacobs', 'NJ Rimmington', 'Sunny Singh',
       'AL Menaria', 'WD Parnell', 'JJ van der Wath', 'R Ninan',
       'S Aravind', 'MS Wade', 'TD Paine', 'JEC Franklin', 'SB Wagh',
       'AC Thomas', 'Shakib Al Hasan', 'DH Yagnik', 'S Randiv',
       'BJ Haddin', 'NLTC Perera', 'NL McCullum', 'JE Taylor',
       'J Syed Mohammad', 'RN ten Doeschate', 'TR Birt', 'AG Murtaza',
       'Harpreet Singh', 'M Klinger', 'AC Blizzard', 'I Malhotra',
       'L Ablish', 'CA Ingram', 'S Nadeem', 'P Parameswaran',
       'CJ Ferguson', 'VR Aaron', 'AA Chavan', 'ND Doshi', 'B Kumar',
       'Y Gnaneswara Rao', 'S Rana', 'BA Bhatt', 'F du Plessis',
       'RE Levi', 'GJ Maxwell', 'SPD Smith', 'SA Yadav', 'MN Samuels',
       'KK Cooper', 'JP Faulkner', 'HV Patel', 'DAJ Bracewell',
       'DJ Harris', 'Ankit Sharma', 'SP Narine', 'GB Hogg', 'RR Bhatkal',
       'CJ McKay', 'N Saini', 'DA Miller', 'Azhar Mahmood', 'P Negi',
       'RJ Peterson', 'KMDN Kulasekara', 'A Ashish Reddy',
       'V Pratap Singh', 'BB Samantray', 'MJ Clarke', 'Gurkeerat Singh',
       'AP Majumdar', 'PA Reddy', 'K Upadhyay', 'P Awana', 'AD Russell',
       'A Chandila', 'CA Lynn', 'Sunny Gupta', 'MC Juneja', 'KK Nair',
       'GH Vihari', 'R Shukla', 'MDKJ Perera', 'AS Rajpoot', 'B Laughlin',
       'M Vohra', 'JD Unadkat', 'Mohammed Shami', 'BMAJ Mendis',
       'R Rampaul', 'CH Morris', 'SV Samson', 'SMSM Senanayake',
       'BJ Rohrer', 'KL Rahul', 'Q de Kock', 'R Dhawan', 'MG Johnson',
       'LJ Wright', 'IC Pandey', 'CM Gautam', 'X Thalaivan Sargunam',
       'DJG Sammy', 'KW Richardson', 'MM Sharma', 'UA Birla',
       'Parvez Rasool', 'Sandeep Sharma', 'S Kaul', 'Sachin Baby',
       'PV Tambe', 'NM Coulter-Nile', 'CJ Anderson', 'NJ Maddinson',
       'AR Patel', 'JJ Bumrah', 'JDS Neesham', 'TG Southee', 'MA Starc',
       'BR Dunk', 'RR Rossouw', 'Shivam Sharma', 'YS Chahal',
       'LMP Simmons', 'VH Zol', 'Imran Tahir', 'BCJ Cutting',
       'BE Hendricks', 'S Gopal', 'M de Lange', 'R Tewatia', 'JO Holder',
       'Karanveer Singh', 'SS Iyer', 'DJ Hooda', 'Anureet Singh',
       'KS Williamson', 'SA Abbott', 'J Suchith', 'RG More', 'D Wiese',
       'HH Pandya', 'SN Khan', 'MJ McClenaghan', 'DJ Muthuswami',
       'PJ Cummins', 'SN Thakur', 'JC Buttler', 'CR Brathwaite',
       'MP Stoinis', 'Ishan Kishan', 'C Munro', 'P Sahu', 'KH Pandya',
       'AD Nath', 'MJ Guptill', 'KJ Abbott', 'TM Head', 'M Ashwin',
       'NS Naik', 'RR Pant', 'SW Billings', 'KC Cariappa',
       'PSP Handscomb', 'Swapnil Singh', 'J Yadav', 'UT Khawaja',
       'HM Amla', 'F Behardien', 'A Zampa', 'BB Sran', 'N Rana',
       'S Kaushik', 'ER Dwivedi', 'CJ Jordan', 'A Choudhary', 'TS Mills',
       'BA Stokes', 'JJ Roy', 'Vishnu Vinod', 'Basil Thampi', 'CR Woakes',
       'RA Tripathi', 'DL Chahar', 'V Shankar', 'Rashid Khan',
       'LH Ferguson', 'RD Chahar', 'C de Grandhomme', 'AF Milne',
       'S Badree', 'Mohammad Nabi', 'AJ Tye', 'K Rabada', 'Kuldeep Yadav',
       'Washington Sundar', 'DM Bravo', 'AR Bawne', 'SP Jackson',
       'Ankit Soni', 'TA Boult', 'E Lewis', 'MA Wood', 'RK Singh',
       'DJM Short', 'K Gowtham', 'TK Curran', 'M Markande', 'B Stanlake',
       'Mujeeb Ur Rahman', 'A Dananjaya', 'Shivam Mavi', 'Shubman Gill',
       'Mohammed Siraj', 'H Klaasen', 'RK Bhui', 'JC Archer', 'PP Shaw',
       'LE Plunkett', 'Mustafizur Rahman', 'AD Hales', 'MK Lomror',
       'DR Shorey', 'MM Ali', 'M Prasidh Krishna', 'P Chopra',
       'JPR Scantlebury-Searles', 'Abhishek Sharma', 'IS Sodhi',
       'SO Hetmyer', 'S Dube', 'NA Saini', 'JM Bairstow', 'Rasikh Salam',
       'KMA Paul', 'N Pooran', 'P Ray Barman', 'S Lamichhane',
       'SM Curran', 'GC Viljoen', 'Avesh Khan', 'HF Gurney', 'SD Lad',
       'AS Joseph', 'MJ Santner', 'R Parag', 'JL Denly', 'LS Livingstone',
       'KK Ahmed', 'AJ Turner', 'SE Rutherford', 'Harpreet Brar',
       'Y Prithvi Raj', 'P Simran Singh', 'JL Pattinson', 'A Nortje',
       'T Banton', 'D Padikkal', 'YBK Jaiswal', 'RD Gaikwad',
       'TU Deshpande', 'Abdul Samad', 'PK Garg', 'JR Philippe',
       'Kartik Tyagi', 'CV Varun', 'KL Nagarkoti', 'I Udana',
       'Ravi Bishnoi', 'Shahbaz Ahmed', 'AT Carey', 'N Jagadeesan',
       'T Natarajan', 'P Dubey', 'SS Cottrell', 'Arshdeep Singh',
       'DR Sams'], dtype=object)

In [ ]:
df_rohit =deliveries_data[deliveries_data['batsman']=='RG Sharma']

In [ ]:
df_rohit

,id,inning,over,ball,batsman,non_striker,bowler,batsman_runs,extra_runs,total_runs,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team
1070,335986,1,8,2,RG Sharma,A Symonds,M Kartik,0,0,0,0,0,NaN,NaN,NaN,NaN,Deccan Chargers,Kolkata Knight Riders
1071,335986,1,8,3,RG Sharma,A Symonds,M Kartik,0,0,0,0,0,NaN,NaN,NaN,NaN,Deccan Chargers,Kolkata Knight Riders
1072,335986,1,8,4,RG Sharma,A Symonds,M Kartik,0,0,0,0,1,caught,RG Sharma,WP Saha,NaN,Deccan Chargers,Kolkata Knight Riders
1458,335988,1,13,3,RG Sharma,SB Bangar,VY Mahesh,1,0,1,0,0,NaN,NaN,NaN,NaN,Deccan Chargers,Delhi Daredevils
1460,335988,1,13,5,RG Sharma,SB Bangar,VY Mahesh,1,0,1,0,0,NaN,NaN,NaN,NaN,Deccan Chargers,Delhi Daredevils
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193355,1237181,2,15,1,RG Sharma,Ishan Kishan,P Dubey,1,0,1,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals
193359,1237181,2,15,5,RG Sharma,Ishan Kishan,P Dubey,0,0,0,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals
193360,1237181,2,15,6,RG Sharma,Ishan Kishan,P Dubey,1,0,1,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals
193361,1237181,2,16,1,RG Sharma,Ishan Kishan,A Nortje,0,0,0,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals
193362,1237181,2,16,2,RG Sharma,Ishan Kishan,A Nortje,0,0,0,0,1,caught,RG Sharma,Lalit Yadav (sub),NaN,Mumbai Indians,Delhi Capitals

In [ ]:
df_rohit.columns

Index(['id', 'inning', 'over', 'ball', 'batsman', 'non_striker', 'bowler',
       'batsman_runs', 'extra_runs', 'total_runs', 'non_boundary', 'is_wicket',
       'dismissal_kind', 'player_dismissed', 'fielder', 'extras_type',
       'batting_team', 'bowling_team'],
      dtype='object')

In [ ]:
df_rohit['dismissal_kind'].value_counts() #how hitman got out

dismissal_kind
caught               112
bowled                23
run out               20
lbw                   12
caught and bowled      7
stumped                3
Name: count, dtype: int64

In [ ]:
len(df_rohit[df_rohit['batsman_runs']==1]) ## Total runs scored by taking singles ie 1's

1663

In [ ]:
len(df_rohit[df_rohit['batsman_runs']==2])*2 ## Total runs scored by taking doubles ie 2's

428

In [ ]:
len(df_rohit[df_rohit['batsman_runs']==3])*3 ## Total runs scored by taking triples ie 3's

18

In [ ]:
len(df_rohit[df_rohit['batsman_runs']==4])*4 ## Total runs scored by hitting boundaries ie 4's

1832

In [ ]:
len(df_rohit[df_rohit['batsman_runs']==6])*6 ## Total runs scored by hitting sixes ie 6's

1284

In [ ]:
import plotly.express as px

In [ ]:
# Plot the above runs stats

In [ ]:
import plotly.graph_objects as go

values = [866, 226, 6, 820, 678]

labels = [
    "Singles (1 run)",
    "Doubles (2 runs)",
    "Triples (3 runs)",
    "Fours (4 runs)",
    "Sixes (6 runs)"
]

trace = go.Pie(
    labels=labels,
    values=values,
    textinfo='label+percent+value',
    hovertemplate=
        "<b>%{label}</b><br>" +
        "Runs Scored: %{value}<br>" +
        "Percentage: %{percent}<extra></extra>"
)

fig = go.Figure(data=[trace])

fig.update_layout(
    title="Runs Distribution by Shot Type for Rohit Sharma"
)

fig.show()

# **CONCLUSION**

**Most of the runs scored by Rohit Sharma come from singles and boundaries (fours and sixes), indicating a batting style that balances effective strike rotation with aggressive power hitting. Contributions from doubles and triples are comparatively minimal, suggesting a stronger reliance on boundary scoring and consistent accumulation through singles.**

## Section 2 — Does Winning the Toss Imply Winning the Match?

In [ ]:
match_data.columns

Index(['id', 'city', 'date', 'player_of_match', 'venue', 'neutral_venue',
       'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'result',
       'result_margin', 'eliminator', 'method', 'umpire1', 'umpire2'],
      dtype='object')

In [ ]:
match_data[['team1', 'team2' , 'toss_winner' , 'winner']]

,team1,team2,toss_winner,winner
0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders
1,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,Chennai Super Kings
2,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,Delhi Daredevils
3,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,Royal Challengers Bangalore
4,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,Kolkata Knight Riders
...,...,...,...,...
811,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,Royal Challengers Bangalore
812,Mumbai Indians,Delhi Capitals,Delhi Capitals,Mumbai Indians
813,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,Sunrisers Hyderabad
814,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals
815,Delhi Capitals,Mumbai Indians,Delhi Capitals,Mumbai Indians

In [ ]:
## if "toss_winner" equals to "match_winner" , then assign "Yes" else assign "No"

match_data['toss_win_game_win'] = np.where(match_data['toss_winner']==match_data['winner'] , 'Yes' , 'No')

In [ ]:
match_data.columns

Index(['id', 'city', 'date', 'player_of_match', 'venue', 'neutral_venue',
       'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'result',
       'result_margin', 'eliminator', 'method', 'umpire1', 'umpire2',
       'toss_win_game_win'],
      dtype='object')

In [ ]:
match_data['toss_win_game_win'].value_counts()

toss_win_game_win
Yes    418
No     398
Name: count, dtype: int64

## lets create Pie chart of above values ..

In [ ]:
match_data['toss_win_game_win'].value_counts().index

Index(['Yes', 'No'], dtype='object', name='toss_win_game_win')

In [ ]:
match_data['toss_win_game_win'].value_counts().values

array([418, 398])

In [ ]:
labels = match_data['toss_win_game_win'].value_counts().index
values = match_data['toss_win_game_win'].value_counts().values

trace = go.Pie(labels=labels, values=values)

data = [trace]

fig = go.Figure(data=data)

fig.update_traces(
    labels=['Toss Winner Won Match', 'Toss Winner Lost Match'],
    hoverinfo='label+percent',
    textinfo='label+percent'
)

fig.show()

# CONCLUSION :
Winning the toss may offer an initial advantage, but it does not strongly determine the final match result. Overall team performance plays a much larger role in securing victory.

# Section 3 — Team Win Statistics & Win Percentages

In [ ]:
match_data.columns

Index(['id', 'city', 'date', 'player_of_match', 'venue', 'neutral_venue',
       'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'result',
       'result_margin', 'eliminator', 'method', 'umpire1', 'umpire2',
       'toss_win_game_win'],
      dtype='object')

In [ ]:
match_data.head(5)

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2,toss_win_game_win
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen,No
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri,Yes
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar,No
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper,No
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan,No

In [ ]:
match_data[['team1', 'team2']]

                           team1                        team2
0    Royal Challengers Bangalore        Kolkata Knight Riders
1                Kings XI Punjab          Chennai Super Kings
2               Delhi Daredevils             Rajasthan Royals
3                 Mumbai Indians  Royal Challengers Bangalore
4          Kolkata Knight Riders              Deccan Chargers
..                           ...                          ...
811  Royal Challengers Bangalore               Mumbai Indians
812               Mumbai Indians               Delhi Capitals
813  Royal Challengers Bangalore          Sunrisers Hyderabad
814               Delhi Capitals          Sunrisers Hyderabad
815               Delhi Capitals               Mumbai Indians

[816 rows x 2 columns]

In [ ]:
matches_played = match_data['team1'].value_counts() + match_data['team2'].value_counts()

In [ ]:
type(matches_played)

pandas.core.series.Series

In [ ]:
matches_played_df = matches_played.to_frame().reset_index()

In [ ]:
matches_played_df.columns = ['team_name' , 'Matches_played']

In [ ]:
matches_played_df

                      team_name  Matches_played
0           Chennai Super Kings             178
1               Deccan Chargers              75
2                Delhi Capitals              33
3              Delhi Daredevils             161
4                 Gujarat Lions              30
5               Kings XI Punjab             190
6          Kochi Tuskers Kerala              14
7         Kolkata Knight Riders             192
8                Mumbai Indians             203
9                 Pune Warriors              46
10             Rajasthan Royals             161
11       Rising Pune Supergiant              16
12      Rising Pune Supergiants              14
13  Royal Challengers Bangalore             195
14          Sunrisers Hyderabad             124

In [ ]:
wins = pd.DataFrame(match_data['winner'].value_counts()).reset_index()

In [ ]:
wins.columns = ['team_name' , 'Wins']

In [ ]:
wins

                      team_name  Wins
0                Mumbai Indians   120
1           Chennai Super Kings   106
2         Kolkata Knight Riders    99
3   Royal Challengers Bangalore    91
4               Kings XI Punjab    88
5              Rajasthan Royals    81
6              Delhi Daredevils    67
7           Sunrisers Hyderabad    66
8               Deccan Chargers    29
9                Delhi Capitals    19
10                Gujarat Lions    13
11                Pune Warriors    12
12       Rising Pune Supergiant    10
13         Kochi Tuskers Kerala     6
14      Rising Pune Supergiants     5

In [ ]:
played =matches_played_df.merge(wins, on='team_name' , how='inner' )

In [ ]:
played

                      team_name  Matches_played  Wins
0           Chennai Super Kings             178   106
1               Deccan Chargers              75    29
2                Delhi Capitals              33    19
3              Delhi Daredevils             161    67
4                 Gujarat Lions              30    13
5               Kings XI Punjab             190    88
6          Kochi Tuskers Kerala              14     6
7         Kolkata Knight Riders             192    99
8                Mumbai Indians             203   120
9                 Pune Warriors              46    12
10             Rajasthan Royals             161    81
11       Rising Pune Supergiant              16    10
12      Rising Pune Supergiants              14     5
13  Royal Challengers Bangalore             195    91
14          Sunrisers Hyderabad             124    66

In [ ]:
import plotly.graph_objects as go

# Calculate win %
played['Win_Percentage'] = (
    played['Wins'] / played['Matches_played'] * 100
).round(2)

# Team with highest win %
best_team = played.loc[played['Win_Percentage'].idxmax()]

fig = go.Figure()

fig.add_trace(go.Bar(
    y=played['team_name'],
    x=played['Matches_played'],
    name='Matches Played',
    orientation='h'
))

fig.add_trace(go.Bar(
    y=played['team_name'],
    x=played['Wins'],
    name='Wins',
    orientation='h',
    text=played['Win_Percentage'].astype(str) + '%',
    textposition='outside'
))

fig.update_layout(
    title=(
        f'IPL Teams: Matches Played vs Wins<br>'
        f'<sup>Highest Win %: {best_team["team_name"]} '
        f'({best_team["Win_Percentage"]}%)</sup>'
    ),
    barmode='group',
    xaxis_title='Count',
    yaxis_title='Teams',
    height=700
)

fig.show()

print(
    f"Highest Win Percentage: {best_team['team_name']} "
    f"({best_team['Win_Percentage']}%)"
)

Highest Win Percentage: Rising Pune Supergiant (62.5%)